name: vixbot

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build python 2.7
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8 future
          ./CI/build.sh
